apiVersion: v1
kind: Service
metadata:
  name: app-server
  labels:
    name: app-server
spec:
  type: LoadBalancer
  selector:
    app: app-server
  ports:
    - port: 8080
      name: app-server-port
      protocol: TCP
