apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-server
      id: "o"
  template:
    metadata:
      labels:
        app: app-server
        id: "o"
    spec:
      containers:
        - name: app-server
          image: us-east1-docker.pkg.dev/root-furnace-306909/hadocker-images/ha-server:1.0.0-main
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_INTERNAL_IP
              value: "app-server:8080"
            - name: KAFKA_BROKERCONNECT
              value: "kafka-broker:9092"
      imagePullSecrets:
        - name: gcr-json-key
