---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bjenkinssa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bjenkinssa
subjects:
  - kind: ServiceAccount
    name: bjenkinssa
