apiVersion: v1
kind: Service
metadata:
  name: postgresdb
  labels:
    app: postgres
spec:
  type: LoadBalancer
  selector:
    app: postgresdb
  ports:
    - port: 5432
      name: postgresdb-port
      protocol: TCP
