apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      id: "o"
  template:
    metadata:
      labels:
        app: postgres
        id: "o"
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
          env:
            - name: DB_INTERNAL_IP
              value: "postgres:5432"
      volumes:
      - name: postgresdb
        persistentVolumeClaim:
          claimName: postgres-pvc
