apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
        - name: postgresdb
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdbv
          env:
            - name: DB_INTERNAL_IP
              value: "postgresdb:5432"
      volumes:
      - name: postgresdbv
        persistentVolumeClaim:
          claimName: postgres-pvc
