node:
  name: server
server:
  port: 8080
  datasource:
    initialization-mode: always
kafka:
  bootstrap-address: localhost:29092
  topics:
    node-message: node-message
  consumer:
    group-id: server-consumer
    should-filter-consumer: false
