spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hasdb1?currentSchema=ha_data
    driverClassName: org.postgresql.Driver
    username: ha
    password: hapassha1!
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQL82Dialect
      hibernate:
        ddl-auto: update
