server:
  name: server
  port: 8080
  datasource:
    initialization-mode: always
  error:
    include-stacktrace: always
kafka:
  bootstrap-address: localhost:29092
  topics:
    node-action: node-action
    node-response: node-response
    node-telemetry: node-telemetry
  consumer:
    group-id: server-consumer
    should-filter-consumer: false
management:
  endpoints:
    enabled-by-default: false
