node:
  name: node1
server:
  port: 8090
kafka:
  bootstrap-address: localhost:9092
  topics:
    node-message: node-message
    node-telemetry: node-telemetry
  consumer:
    group-id: node-consumer-1
    should-filter-consumer: true