node:
  name: ${name}
server:
  port: 8090
  version: ${version}
kafka:
  bootstrap-address: localhost:9092
  topics:
    node-message: node-message
    node-telemetry: node-telemetry
  consumer:
    group-id: node-consumer-${name}