apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  labels:
    name: kafka-broker
spec:
  type: LoadBalancer
  ports:
    - port: 9092
      name: kafka-broker-port
      protocol: TCP
  selector:
    app: kafka
    id: "o"
