apiVersion: v1
kind: Service
metadata:
  name: kafdrop-ui
  labels:
    name: kafdrop-ui
spec:
  type: LoadBalancer
  selector:
    app: kafdrop-ui
  ports:
    - port: 9000
      name: kafdrop-ui-port
      protocol: TCP
