apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-server0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-server
  template:
    metadata:
      labels:
        app: zookeeper-server
    spec:
      containers:
        - name: zookeeper-server
          image: confluentinc/cp-zookeeper:latest
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_SERVER_ID
              value: "1"
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
