apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:latest
          ports:
            - containerPort: 2181
          env:
            - ZOOKEEPER_SERVER_ID: 1
                ZOOKEEPER_CLIENT_PORT: 2181
                ALLOW_ANONYMOUS_LOGIN: "yes"
            - name: ZOOKEEPER_SERVER_ID
              value: "1"
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
