hibernate:
  id:
    new_generator_mappings: true
logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
server:
  port: 8087
spring:
  datasource:
    url: jdbc:h2:file:./build/db/spring-datasource
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
    showSql: true
    formatSql: true
    hbm2ddlAuto: update
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
