version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: {{ ip_address }} # /sbin/ip route|awk '/default/ { print $3 }'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - {{ docker_sock }}:/var/run/docker.sock # typically /var/run/docker.sock:/var/run/docker.sock
      - {{ kafka_volume }}:/kafka # typically /kafka or ./kafka
  kafdrop:
    image: obsidiandynamics/kafdrop
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: {{ ip_address }}:9092 # /sbin/ip route|awk '/default/ { print $3 }'
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
